pardakht/urls.py
from django.conf.urls import url
from . import views

app_name = 'pardakht'
urlpatterns = [
    url(r'^p/(?P<slug>\w+)/$', views.start_payment, name='start_payment'),
    url(r'^t/(?P<slug>\w+)/(?P<gateway>\w+)/$', views.select_gateway, name='select_gateway'),
    url(r'^w/(?P<slug>\w+)/(?P<gateway>\w+)/$', views.select_walleta, name='select_walleta'),
    url(r'^w/(?P<slug>\w+)/(?P<gateway>\w+)/$', views.select_ghesta, name='select_ghesta'),
    url(r'^r/(?P<slug>\w+)/(?P<gateway>\w+)', views.called_back, name='callback_url')
]

pardakht/models.py
from django.contrib.auth.models import User
from django.db import models
from django_extensions.db.fields import RandomCharField


class Payment(models.Model):
    STATE_CREATED = 'created'
    STATE_OPENED = 'opened'
    STATE_BANK = 'bank'
    STATE_SUCCESS = 'successful'
    STATE_FAILURE = 'unsuccessful'
    STATE_CHOICES = (
        (STATE_CREATED, 'Created'),
        (STATE_OPENED, 'Opened'),
        (STATE_BANK, 'Sent to bank'),
        (STATE_SUCCESS, 'Successful payment'),
        (STATE_FAILURE, 'Unsuccessful payment')
    )

    price = models.PositiveIntegerField()
    token = models.CharField(max_length=500, unique=True, null=True, blank=True)
    slug = RandomCharField(length=8, unique=True)
    trace_number = RandomCharField(length=8, unique=True, include_alpha=False)
    state = models.CharField(max_length=30, choices=STATE_CHOICES, default=STATE_CREATED)
    payment_result = models.CharField(max_length=256, null=True, blank=True)
    verification_result = models.CharField(max_length=256, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    gateway = models.CharField(max_length=256, null=True)
    description = models.CharField(max_length=1024, null=True)
    login_required = models.BooleanField(default=False)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    ref_number = models.CharField(max_length=200, null=True, unique=True)

    # Returning user to your website
    callable_module = models.CharField(max_length=300, null=True)
    callable_name = models.CharField(max_length=100, null=True)
    return_url = models.CharField(max_length=1024, null=True)

    def verification_done(self):
        return self.state in [self.STATE_SUCCESS, self.STATE_FAILURE]

    def successful(self):
        return self.state == self.STATE_SUCCESS

    class Meta:
        app_label = 'pardakht'

pardakht/views.py
import importlib
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from pardakht import gateways
from pardakht.decorators import payment_exists, payment_not_started
from pardakht.models import Payment
import logging
logger = logging.getLogger("django")

@login_required
def go_login(request):
    return redirect(str(request.build_absolute_uri()).replace('http://', 'https://'))

@payment_exists
@payment_not_started
def start_payment(request, slug):
    payment = Payment.objects.get(slug=slug)
    payment.state = Payment.STATE_OPENED
    payment.save()

    gways = list()
    for gway in gateways.actives:
        if getattr(settings, str(gway+'_merchant_id').upper(), None) not in [None, '']:
            gway_module = importlib.import_module('pardakht.gateways.'+gway)
            gways.append({'name': gway_module.name, 'display_name': gway_module.display_name})

    return render(request, 'pardakht/start_payment.html', {'payment': payment, 'gateways': gways})


@payment_exists
@payment_not_started
def select_gateway(request, slug, gateway):
    if gateway not in gateways.actives:
        raise Http404

    payment = Payment.objects.get(slug=slug)

    if request.user.is_authenticated:
        payment.user = request.user
    elif payment.login_required:
        return go_login(request)
    gateway_module = importlib.import_module('.'.join([gateways.__name__, gateway]))
    token = gateway_module.get_token(request, payment)
    if token is None:
        return render(request, 'pardakht/errors/none_token.html',{
                                'errors' : {}
                                })
    payment.state = Payment.STATE_BANK
    payment.token = token
    payment.save()
    return render(request, 'pardakht/redirect_form.html', {
        'url': gateway_module.redirect_url(payment),
        'data': gateway_module.redirect_data(request, payment)
    })


@csrf_exempt
@payment_exists
@payment_not_started
def select_walleta(request, slug, gateway):
    data = request.POST
    if not data:
        raise Http404
    payment = Payment.objects.get(slug=slug)
    if request.user.is_authenticated:
        payment.user = request.user
    elif payment.login_required:
        return go_login(request)
    gateway_module = importlib.import_module('.'.join([gateways.__name__, gateway]))
    token, error = gateway_module.get_token(request, payment, data)
    if not token:
        return render(request, 'pardakht/errors/none_token.html',{
                                'errors' : error
                                }
        )
    payment.state = Payment.STATE_BANK
    payment.token = token
    payment.save()
    return render(request, 'pardakht/redirect_form.html', {
        'url': gateway_module.redirect_url(payment),
        'data': {}
    })

@csrf_exempt
@payment_exists
@payment_not_started
def select_ghesta(request, slug, gateway):
    data = request.POST
    if not data:
        raise Http404
    payment = Payment.objects.get(slug=slug)
    if request.user.is_authenticated:
        payment.user = request.user
    elif payment.login_required:
        return go_login(request)
    gateway_module = importlib.import_module('.'.join([gateways.__name__, gateway]))
    token, error = gateway_module.get_token(request, payment, data)
    if not token:
        return render(request, 'pardakht/errors/none_token.html',{
                                'errors' : error
                                }
        )
    payment.state = Payment.STATE_BANK
    payment.token = token
    payment.save()
    return render(request, 'pardakht/redirect_form.html', {
        'url': gateway_module.redirect_url(payment),
        'data': {}
    })

@csrf_exempt
@payment_exists
def called_back(request, slug, gateway):
    payment = Payment.objects.get(slug=slug)
    if payment.verification_done():
        return render(request, 'pardakht/errors/verified_before.html', {'payment':None})
    if payment.user is None and request.user.is_authenticated:
        payment.user = request.user
        payment.save()
    gateway_module = importlib.import_module('.'.join([gateways.__name__, gateway]))
    gateway_module.verify(request, payment)
    logger.debug(gateway_module)
    if payment.callable_module is not None and payment.callable_name is not None:
        user_module = importlib.import_module(payment.callable_module)
        return_function = getattr(user_module, payment.callable_name)
        try:
            return_function(payment)
        except Exception as e:
            lg = logging.getLogger(__name__)
            lg.debug("Something went wrong with given callback function")
            lg.debug(str(e))

    return render(request, 'pardakht/payment_result.html', {'payment': payment})

pardakht/templates/pardakht/base.html
{% load static %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html lang="fa">
<head>
    <title>پرداخت</title>
    <meta content="text/html" charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link
            rel="stylesheet"
            href="{% static 'pardakht/semantic/semantic.rtl.min.css' %}"
    >
    <link rel="stylesheet" href="{% static 'pardakht/css/styles.css' %}">
    <script src="{% static 'pardakht/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'pardakht/semantic/semantic.min.js' %}"></script>
    <script src="{% static 'pardakht/js/scripts.js' %}"></script>
    <script src="{% static 'pardakht/js/index.js' %}"></script>
    <link rel="stylesheet" href="{% static 'pardakht/css/main.css' %}">

    {% block extra_header %}{% endblock %}
</head>
<body dir="rtl" style="background-color: #ebebeb">
    {% block body %}
        <div class="ui container" style="margin-top: 2em; width: 60vw;">
            {% block container %}
            {% endblock %}
        </div>
        <div>
          {% block walleta %}
          {% endblock %}
          </div>
          <div >
            {% block ghesta %}
            {% endblock %}
          </div>
    {% endblock %}
</body>
</html>

pardakht/templates/pardakht/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pardakht</title>
    <script src="index.js"></script>
    <link rel="stylesheet" href="main.css">
</head>
<body>
<div>
    <button id="btn_pay">Open Modal</button>
    <div id="form_modal">
        <form id="pay_form">
            <label for="name">
                نام
                <input name="name" id="name" type="text" required>
            </label>
            <label for="lastname">
                نام خانوادگی
                <input name="lastname" id="lastname" type="text" required>
            </label>
            <label for="code">
                کد ملی
                <input name="code" id="code" type="number" required>
            </label>
            <button type="submit">ارسال</button>
        </form>
    </div>
</div>
</body>
</html>

pardakht/templates/pardakht/payment_result.html
{% extends 'pardakht/base.html' %}

{% block container %}
    <div class="ui fluid raised blue segment">
        <div class="ui header">
            نتیجه پرداخت
        </div>
        <div class="ui relaxed divided list">
            <div class="item">
                <i class="large money bill alternate outline middle aligned icon"></i>
                <div class="content">
                    <a class="header">مبلغ پرداخت</a>
                    <div class="description" style="margin-top: 7px;">{{ payment.price }} تومان</div>
                </div>
            </div>
            <div class="item">
                <i class="large file outline middle aligned icon"></i>
                <div class="content">
                    <a class="header">توضیحات پرداخت</a>
                    <div class="description" style="margin-top: 7px;">{{ payment.description }}</div>
                </div>
            </div>
            <div class="item">
                <div class="content">
                    <div class="header">شماره پیگیری</div>
                    <div class="description" style="margin-top: 7px;">{{ payment.trace_number }}</div>
                </div>
            </div>
        </div>
        <div class="ui {% if payment.successful %}green{% else %}red{% endif %} message">
            پرداخت با موفقیت انجام {% if payment.successful %}شد!{% else %}نشد {% endif %}
        </div>
        {% if payment.return_url is not None %}
            <a class="ui blue labeled icon button" href="{{ payment.return_url }}">
                <i class="right arrow icon"></i>
            بازگشت
            </a>
        {% endif %}
    </div>
    <script>
        window.addEventListener("load", function () {
        const button = document.querySelector(".button")
        setTimeout(function () {
        button.click()
    }, 5000)
    })
    </script>

{% endblock %}

pardakht/templates/pardakht/redirect_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
  {% if 'vandar' in url or 'walleta' in url or 'ghesta' in url %}
  <form id="bank-form" method="get" action="{{ url }}">

      {% for key, value in data.items %}
          <input type="hidden" name="{{ key }}" value="{{ value }}">
      {% endfor %}

  </form>
  {% else %}


<form id="bank-form" method="post" action="{{ url }}">

    {% for key, value in data.items %}
        <input type="hidden" name="{{ key }}" value="{{ value }}">
    {% endfor %}

</form>
{% endif %}
<script>
    document.getElementById('bank-form').submit();
</script>
</body>
</html>

pardakht/templates/pardakht/start_payment.html
{% extends 'pardakht/base.html' %}

{% block container %}
    <div class="ui fluid raised blue segment">
        <div class="ui header">
            اطلاعات پرداخت
        </div>
        <div class="ui relaxed divided list">
            <div class="item">
                <i class="large money bill alternate outline middle aligned icon"></i>
                <div class="content">
                    <a class="header">مبلغ پرداخت</a>
                    <div class="description" style="margin-top: 7px;">{{ payment.price }} تومان </div>
                </div>
            </div>
            <div class="item">
                <i class="large file outline middle aligned icon"></i>
                <div class="content">
                    <a class="header">توضیحات پرداخت</a>
                    <div class="description" style="margin-top: 7px;">{{ payment.description }}</div>
                </div>
            </div>
        </div>
        <div>
            {% for gateway in gateways %}
                <a class="ui large blue button" style="margin-bottom: 1rem;" href="{% url 'pardakht:select_gateway' payment.slug gateway.name %}">
                    پرداخت از طریق {{ gateway.display_name }}
                </a>
                {% empty %}
                درگاهی تعریف نشده است!
            {% endfor %}
            <a class="ui large blue button", id="btn_pay_walleta">درگاه اقساطی ولتا</a>
            <a class="ui large blue button", id="btn_pay_ghesta">درگاه اقساطی قسطا</a>

        </div>
    </div>

{% endblock %}
{% block walleta %}
<div>
    <div id="form_modal_walleta">
        <form id="pay_form_walleta">
          <p>برای استفاده از درگاه والتا، در ابتدا باید در این سایت حساب کاربری ساخته و پس از آن در هنگام پرداخت اطلاعات خود را در سایت ایگرد وارد نمایید.</p>
            <label for="name">
                نام
                <input name="payer_first_name" id="name" type="text" required>
            </label>
            <label for="lastname">
                نام خانوادگی
                <input name="payer_last_name" id="lastname" type="text" required>
            </label>
            <label for="code">
                کد ملی
                <input name="payer_national_code" id="code" type="number" required>
            </label>
            <label for="phone">
                تلفن همراه
                <input name="payer_mobile" id="phone" type="number" required>
            </label>
            <input id="slug" name="slug"  type="hidden" value="{{ payment.slug }}">
            <input id="gateway" name="gateway"  type="hidden" value="walleta">



            <button type="submit"><p class='sub_text'>ارسال</p></button>
            <button type="button", id="close">خروج</button>

        </form>
    </div>
</div>
{% endblock %}
{% block ghesta %}
<div>
    <div id="form_modal_ghesta">
        <form id="pay_form_ghesta">
            <p>برای استفاده از درگاه قسطا، در ابتدا باید در این سایت حساب کاربری ساخته و پس از آن در هنگام پرداخت اطلاعات خود را در سایت ایگرد واربد نمایید.</p>
            <label for="name">
                نام و نام خانوادگی
                <input name="‫‪payerName‬‬" id="name" type="text" required>
            </label>

            <label for="‫‪payerIndentity‬‬">
                تلفن همراه
                <input name="payer_mobile" id="phone" type="number" required>
            </label>
            <input id="slug" name="slug"  type="hidden" value="{{ payment.slug }}">
            <input id="gateway" name="gateway"  type="hidden" value="ghesta">

            <button type="submit"><p class='sub_text'>ارسال</p></button>
            <button type="button", id="close">خروج</button>

        </form>
    </div>
</div>
{% endblock %}